ДЗ 6: эмулятор банкомата
Bryantsev/otus-java pull request #6
Opened 2019-09-09 21:18 UTC by Bryantsev

2019-09-11 18:53 UTC, kataus requested changes

2019-09-11 18:53 UTC, kataus commented on hw06-atm/src/test/java/ru/otus/lesson11/AtmTest.java
> +package ru.otus.lesson11;
Тесты не работают из  maven.
-------------------------------------------------------
 T E S T S
-------------------------------------------------------

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

2019-09-11 18:53 UTC, kataus commented on hw06-atm/src/main/java/ru/otus/lesson11/money_cells/MoneyCellC500N500.java
> +public class MoneyCellC500N500 extends AbstractMoneyCell {
Не очень удачное решение зашивать жестко номинал ячейки в класс. В этом варианте при добавлении новой купюры в процессинг придется делать новую версию кода.

2019-09-11 18:53 UTC, kataus commented on hw06-atm/src/main/java/ru/otus/lesson11/money_cells/MoneyCell.java
> +    public default int getCapacityRemained() {
default в интерфейсах не очень красиво, опасно, но терпимо. Вот только какой смысл делать их если мы всё равно дальше работаем с абстрактным классом и может в нем всё это сделать. Чтобы вся общая логика была в одном месте

2019-09-11 18:53 UTC, kataus commented on hw06-atm/src/main/java/ru/otus/lesson11/money_cells/CustomMoneyCell.java
> +    public void setCapacity(int capacity) {
Смотрите, по бизнес логике - ну не может в течении жизни ячейки измениться номинал или размер ячейки. Так что эти поля стоит сделать иммутабельными

2019-09-11 18:53 UTC, kataus commented on hw06-atm/src/main/java/ru/otus/lesson11/money_cells/CustomMoneyCell.java
> +    public void setNominal(int nominal) {
Зачем переписали функцию на точно такую же как выше по уровням абстракции

2019-09-11 18:53 UTC, kataus commented on hw06-atm/src/main/java/ru/otus/lesson11/Atm.java
> +    public Atm() {
Такая инициализация класса приведет к большому количеству ошибок при попытке обратиться к методам. НАдо или убрать конструктор или переделать так, чтобы он приводил класс в корректное состояние

2019-09-11 18:53 UTC, kataus commented on hw06-atm/src/main/java/ru/otus/lesson11/Atm.java
> +public class Atm<T extends AbstractMoneyCell> {
Идея использовать тут Generic - не очевидна. Более того - излишне. Коллеги могут по ошибке зашить на конкретную реализацию. более того, зачем банкомату вовне вообще знать о нюансах используемых ячеек. С одной стороны в инструкции для техперсонала это надо, но не надо совершенно пользователям.

2019-09-11 18:53 UTC, kataus commented on hw06-atm/src/main/java/ru/otus/lesson11/Atm.java
> +public class Atm<T extends AbstractMoneyCell> {
Хорошо бы выделить банкомат в интерфейс, которым смогут пользоваться клиенты. И дальше уже работать с интерфейсом (хотя уже в следующем ДЗ)

2019-09-11 19:55 UTC, Bryantsev commented on hw06-atm/src/test/java/ru/otus/lesson11/AtmTest.java
> +package ru.otus.lesson11;
Исправил

2019-09-11 19:57 UTC, Bryantsev commented on hw06-atm/src/main/java/ru/otus/lesson11/money_cells/MoneyCellC500N500.java
> +public class MoneyCellC500N500 extends AbstractMoneyCell {
Не совсем верно понял описание ДЗ. Хотел показать, что банкомат работает с разными реализациями ячеек, используя интерфейс. Отчасти эти классы являются аналогом конкретных моделей ячеек, а не их общими абстракциями. Удалил неправильные ячейки

2019-09-11 19:59 UTC, Bryantsev commented on hw06-atm/src/main/java/ru/otus/lesson11/money_cells/MoneyCell.java
> +    public default int getCapacityRemained() {
Зачем тогда вообще их придумали ) Тут они вроде бы логично подходят для интерфейса, т.к. используют только методы интерфейса. Но согласен, при наличии абстрактного класса лучше всю логику держать вместе. Исправил.

2019-09-11 20:00 UTC, Bryantsev commented on hw06-atm/src/main/java/ru/otus/lesson11/money_cells/CustomMoneyCell.java
> +    public void setCapacity(int capacity) {
Это я погорячился из предположения, что потом объект будет создаваться ORM'ом, а там нужен конструктор без параметров и сеттеры на поля. Удалил

2019-09-11 20:01 UTC, Bryantsev commented on hw06-atm/src/main/java/ru/otus/lesson11/money_cells/CustomMoneyCell.java
> +    public void setNominal(int nominal) {
Аналогично тому, что выше. Переписал, т.к. расширил видимость до public с protected для будущего использования с ORM'ом. Удалил

2019-09-11 20:02 UTC, Bryantsev commented on hw06-atm/src/main/java/ru/otus/lesson11/Atm.java
> +    public Atm() {
Удалил конструктор и инициализирую пустой список ячеек, если он приходит равным null. Хотя тут возможно имеет смысл кидать исключение, но т.к. ТЗ не настолько детальное, то пойдем простым путем.

2019-09-11 20:03 UTC, Bryantsev commented on hw06-atm/src/main/java/ru/otus/lesson11/Atm.java
> +public class Atm<T extends AbstractMoneyCell> {
Действительно переборщил. Удалил генерик.

2019-09-11 20:04 UTC, Bryantsev commented on hw06-atm/src/main/java/ru/otus/lesson11/Atm.java
> +public class Atm<T extends AbstractMoneyCell> {
Выделил по аналогии с ячейкой.

2019-09-12 12:11 UTC, kataus commented on hw06-atm/src/main/java/ru/otus/lesson11/money_cells/MoneyCell.java
> +    public default int getCapacityRemained() {
Скажу честно - мне не нравятся default методы в интерфейсах, потребность в них попахивает ошибками в архитектуре. Но многим нравятся, я не насаживаю своё мнение сильно вне своих проектов. Но вот размазывать функционал на 2 файла - точно не айс

2019-09-12 12:12 UTC, kataus approved these changes

2019-09-12 16:31 UTC, merged